---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'A template is for creating lambda '
Resources:
  LambdaFunResource:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Function1
      Code:
        ZipFile:
          Fn::Join:
          - "\n"
          - - 'def lambda_handler(event, context):'
            - "    print('THIS IS LAMBDA CREATED FROM CloudFormation')"
            - "    return 'success'"
      Description: Used to run job
      Handler: index.lambda_handler
      Role: arn:aws:iam::940606869687:role/lambda_role
      Runtime: python3.9
      Timeout: 120
